# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Set environment variables for Airflow
ENV AIRFLOW_HOME=/usr/local/airflow

# Install Airflow
RUN pip install apache-airflow

# Expose the port for Airflow
EXPOSE 8080

# Default command for running Airflow webserver
CMD ["airflow", "webserver"]
